layout : default
auto: true
pygments: true
paginate: 10
markdown: rdiscount

source:      .
destination: ./_site
plugins:     ./_plugins

exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - config.ru

name: Sascha Faun Winter

header_navigation:
    - name: Home
      url:  /
    - name: Resume
      url:  /resume.html
    - name: Contact
      url:  /contact.html

external_links:
    - name: Twitter
      url:  https://twitter.com/faunzy
    - name: LinkedIn
      url:  http://www.linkedin.com/in/saschawinter
    - name: Flickr
      url:  http://flickr.com/faunzy
    - name: Instagram
      url: http://instagram.com/faunzy
    - name: GitHub
      url:  https://github.com/faun
